### ISSUE TITLE
Module twin set in deployment manifest was not set

### ISSUE THREAD

**Issue by fabinshen** [Azure/iotedgehubdev#168]
We wrote a deployment json file with some properties.desired in our modules, as {module1} below. We expected that the desired properties of {module1} will be populated into the module twin, for real deployment through azure IotHub, and local debug through iotedgehubdev simulator. However, we found that the desired properties of {module1} doesn't seem to be set in module twin when running the solution inside iotedgehubdev simulator. Isn't it a bug? or are we missing anything?
{
    "modulesContent": {
        "$edgeAgent": { // required
            "properties.desired": {
            }
        },
        "$edgeHub": { //required
            "properties.desired": {
            }
        },
        "{module1}": {  // optional
            "properties.desired": {
                // desired properties of {module1}
            }
        }
    }
}

**Comment by adashen** [comment]
@fabinshen , Thanks for the issue！Module twin currently is not supported in iotedgehubdev. Since setting module twin needs IoT Hub connection string. However, in iotedgehubdev, we only get the device connection string. The work around is you could use the "iot hub toolkit" in visual studio code to set the module twin.
