### ISSUE TITLE
"File in use by another process" when running IoT Edge Module in VS

### ISSUE THREAD

**Issue by pkoronawa** [Azure/iotedgehubdev#230]
Intermittently, running an IoT Edge module as the startup project in Visual Studio will fail with the message

This seems to persist until host machine is rebooted. I note in the docker log instances of debug FIXME messages.

**Comment by pkoronawa** [comment]
Sorry wrong screen capture

![Capture](https://user-images.githubusercontent.com/47200230/67614237-3938d580-f76e-11e9-87eb-c853917b0923.PNG)

**Comment by adashen** [comment]
@pkoronawa It seems an issue in docker for win. Some issue links:
https://stackoverflow.com/questions/53836103/failed-to-create-endpoint-on-network-nat-hnscall-failed-in-win32-the-process-c
https://github.com/docker/for-win/issues/667

**Comment by pkoronawa** [comment]
They seem to think that it's an issue with whatever calls the docker daemon. Perhaps the relevant section of the docker log helps? Note entries for FIXME at [14:56:35.707]

[dockerFIXME.txt](https://github.com/Azure/iotedgehubdev/files/3780331/dockerFIXME.txt)

**Comment by SLdragon** [comment]
Hi, @pkoronawa , before you start an IoT Edge module, make sure you have already cleaned docker containers in another platform.

For example, if you are running IoT Edge module in Windows container, then switch to the Linux container, you should clean the Windows containers before switch to Linux. Otherwise, it would throw "The process cannot access the file because it is being used by another process" error.

If you are using moby and docker simultaneously, you should also clean it before switching.

**Comment by pkoronawa** [comment]
This occurs when using only windows containers on docker. My module isn't running in a container at all, only test support containers

~~~
CONTAINER ID        IMAGE                                                  COMMAND                  CREATED             STATUS              PORTS                                                                  NAMES
4edcbe14835e        mcr.microsoft.com/azureiotedge-testing-utility:1.0.0   "node server.js"         50 seconds ago      Up 46 seconds       0.0.0.0:53000->3000/tcp                                                input
46266249bdc3        mcr.microsoft.com/azureiotedge-hub:1.0                 "dotnet Microsoft.Az…"   52 seconds ago      Up 50 seconds       0.0.0.0:443->443/tcp, 0.0.0.0:5671->5671/tcp, 0.0.0.0:8883->8883/tcp   edgeHubDev
~~~

**Comment by SLdragon** [comment]
Hi, @pkoronawa , when you try to debug edge module in the visual studio, the module is just running on your host machine, and not in the containers, so you cannot find the module in the container. From your container information, it works fine.

If you already cleaned the containers in other platform and stilll see the error. I think it is because some ports on your system have been occupied, you can check these ports : 53000, 443, 5671, 8883

**Comment by SLdragon** [comment]
If you have any other questions, feel free to contact us. Just close this issue
