### ISSUE TITLE
Failed to install on Python 3.7.3 [Windows]

### ISSUE THREAD

**Issue by wijkjh** [Azure/iotedgehubdev#257]
Running `pip install --upgrade iotedgehubdev` fails on Python 3.7.3, 3.7.5 and 3.7.6rc1 on Windows 10.

Seems to be related to pyaml:
`Building wheels for collected packages: pyyaml
  Building wheel for pyyaml (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\azure-modules\iotedge-moduletest\venv\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\USER\\AppData\\Local\\Temp\\pip-install-kbis1t_o\\pyyaml\\setup.py'"'"'; __file__='"'"'C:\\Users\\USER\\AppData\\Local\\Temp\\pip-install-kbis1t_o\\pyyaml\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\USER\AppData\Local\Temp\pip-wheel-_94b3bmo' --python-tag cp37 ...`

Running `pip install pyyaml>=4.1,<=4.2b4` confirms the issue. 
pyyaml version 4.1 does not exist anymore. And all pyyaml 4.2 version gives the same error.
pyyaml 5.2 installs fine.

**Comment by wijkjh** [comment]
It does work on Linux (WSL).

**Comment by SLdragon** [comment]
Hi, @wijkjh ,  I tried your suggested command for Python 3.7.3, but cannot repro this issue:

![image](https://user-images.githubusercontent.com/5545529/70890098-31373c80-201f-11ea-97ee-92e427682986.png)

We are using pyyaml (4.2b4 ) because the dependency docker-compose is not compatible with pyyaml >=5, and pyyaml < 4 has some vulnerabilities issues. So we can only use 4.2b4 as dependency.

From your error message, seems like build pyyaml failed, you can try to install Visual C++ tools and try again. If you still have issue, you can provide the full error message.

Another workaround is to use standalone iotedgehubdev without Python, you can download it from release page:
![image](https://user-images.githubusercontent.com/5545529/70892439-259a4480-2024-11ea-9e66-239962c3683b.png)

**Comment by SLdragon** [comment]
Hi, @wijkjh , did you solve your problem?

**Comment by SLdragon** [comment]
Hi, wijkjh, I will close this issue, and if you still have problems, feel free to contact us.

**Comment by sacvalleytech** [comment]
Docker-Compose currently supports PyYAML <=5.0 can the dependencies be bumped?
